require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlatformAssistiveTechnologiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlatformAssistiveTechnology. As you add validations to PlatformAssistiveTechnology, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlatformAssistiveTechnologiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all platform_assistive_technologies as @platform_assistive_technologies" do
      platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:platform_assistive_technologies)).to eq([platform_assistive_technology])
    end
  end

  describe "GET #show" do
    it "assigns the requested platform_assistive_technology as @platform_assistive_technology" do
      platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
      get :show, {:id => platform_assistive_technology.to_param}, valid_session
      expect(assigns(:platform_assistive_technology)).to eq(platform_assistive_technology)
    end
  end

  describe "GET #new" do
    it "assigns a new platform_assistive_technology as @platform_assistive_technology" do
      get :new, {}, valid_session
      expect(assigns(:platform_assistive_technology)).to be_a_new(PlatformAssistiveTechnology)
    end
  end

  describe "GET #edit" do
    it "assigns the requested platform_assistive_technology as @platform_assistive_technology" do
      platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
      get :edit, {:id => platform_assistive_technology.to_param}, valid_session
      expect(assigns(:platform_assistive_technology)).to eq(platform_assistive_technology)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PlatformAssistiveTechnology" do
        expect {
          post :create, {:platform_assistive_technology => valid_attributes}, valid_session
        }.to change(PlatformAssistiveTechnology, :count).by(1)
      end

      it "assigns a newly created platform_assistive_technology as @platform_assistive_technology" do
        post :create, {:platform_assistive_technology => valid_attributes}, valid_session
        expect(assigns(:platform_assistive_technology)).to be_a(PlatformAssistiveTechnology)
        expect(assigns(:platform_assistive_technology)).to be_persisted
      end

      it "redirects to the created platform_assistive_technology" do
        post :create, {:platform_assistive_technology => valid_attributes}, valid_session
        expect(response).to redirect_to(PlatformAssistiveTechnology.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved platform_assistive_technology as @platform_assistive_technology" do
        post :create, {:platform_assistive_technology => invalid_attributes}, valid_session
        expect(assigns(:platform_assistive_technology)).to be_a_new(PlatformAssistiveTechnology)
      end

      it "re-renders the 'new' template" do
        post :create, {:platform_assistive_technology => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested platform_assistive_technology" do
        platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
        put :update, {:id => platform_assistive_technology.to_param, :platform_assistive_technology => new_attributes}, valid_session
        platform_assistive_technology.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested platform_assistive_technology as @platform_assistive_technology" do
        platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
        put :update, {:id => platform_assistive_technology.to_param, :platform_assistive_technology => valid_attributes}, valid_session
        expect(assigns(:platform_assistive_technology)).to eq(platform_assistive_technology)
      end

      it "redirects to the platform_assistive_technology" do
        platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
        put :update, {:id => platform_assistive_technology.to_param, :platform_assistive_technology => valid_attributes}, valid_session
        expect(response).to redirect_to(platform_assistive_technology)
      end
    end

    context "with invalid params" do
      it "assigns the platform_assistive_technology as @platform_assistive_technology" do
        platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
        put :update, {:id => platform_assistive_technology.to_param, :platform_assistive_technology => invalid_attributes}, valid_session
        expect(assigns(:platform_assistive_technology)).to eq(platform_assistive_technology)
      end

      it "re-renders the 'edit' template" do
        platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
        put :update, {:id => platform_assistive_technology.to_param, :platform_assistive_technology => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested platform_assistive_technology" do
      platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
      expect {
        delete :destroy, {:id => platform_assistive_technology.to_param}, valid_session
      }.to change(PlatformAssistiveTechnology, :count).by(-1)
    end

    it "redirects to the platform_assistive_technologies list" do
      platform_assistive_technology = PlatformAssistiveTechnology.create! valid_attributes
      delete :destroy, {:id => platform_assistive_technology.to_param}, valid_session
      expect(response).to redirect_to(platform_assistive_technologies_url)
    end
  end

end
